sidebar:
  menu:
    post: '[博客](/)'
    wiki: '[项目](/wiki/)'
    talk: '[动态](/talk/)'
    more: '[更多](/about/)'
  widgets:
    # Recent update
    recent:
      layout: recent
      rss:  /atom.xml
      limit: 5 # Count of posts

# 一款基于 GitHub issues 的开源评论插件
comments:
  service: beaudar
  beaudar:
    repo: xiangshu233/blog-comments

tag_plugins:
  image:
    fancybox: true

open_graph:
  enable: false
  twitter_id: '' # for open_graph meta

# 是否自动生成封面
article:
  auto_cover: false
  # 分类颜色
  category_color:
    '实用脚本': '#DA0F47'
    '笔记': '#03a9f4'
    '解决方案': '#4caf50'
  # 分享
  share: [wechat, weibo, email, link]

# 底部icon
footer:
  social:
    email:
      icon: '<img alt="点我给我发邮件" src="https://fastly.jsdelivr.net/gh/xiangshu233/blogAssets/footer-icon/email.png"/>'
      url: mailto:xiangshu233@outlook.com
    travelling:
      icon: '<img alt="开往下一个世界" src="https://fastly.jsdelivr.net/gh/xiangshu233/blogAssets/footer-icon/travelling.png"/>'
      url: https://travellings.link
    github:
      icon: '<img alt="github" src="https://fastly.jsdelivr.net/gh/xiangshu233/blogAssets/footer-icon/github.png"/>'
      url: https://github.com/xiangshu233
    music:
      icon: '<img alt="我喜欢的音乐" src="https://fastly.jsdelivr.net/gh/xiangshu233/blogAssets/footer-icon/music.png"/>'
      url: https://music.163.com/#/user/home?id=137209982
    comments:
      icon: '<img alt="给我留言" src="https://fastly.jsdelivr.net/gh/xiangshu233/blogAssets/footer-icon/comments.png"/>'
      url: /about/#comments

