sidebar:
  menu:
    post: '[btn.blog](/)'
    wiki: '[btn.wiki](/wiki/)'
    shuoshuo: '[说说](/shuoshuo/)'
    more: '[更多](/about/)'

# 一款基于 GitHub issues 的开源评论插件
comments:
  service: beaudar
  beaudar:
    repo: xiangshu233/blog-comments

tag_plugins:
  image:
    fancybox: true

open_graph:
  enable: false
  twitter_id: '' # for open_graph meta

# 是否自动生成封面
article:
  auto_cover: false
  # 分类颜色
  category_color:
    '新闻稿': '#DA0F47'
    '设计开发': '#03a9f4'
    '解决方案': '#4caf50'
    '博客主题': '#ffa000'
  # 分享
  share: [wechat, weibo, email, link]

# 底部icon
footer:
  social:
    github:
      icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/08a41b181ce68.svg"/>'
      url: https://github.com/xiangshu233
    music:
      icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/3845874.svg"/>'
      url: https://music.163.com/#/user/home?id=173445639
    comments:
      icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/942ebbf1a4b91.svg"/>'
      url: /about/#comments